# Generated by Django 4.2.6 on 2023-11-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1987-07-10'),
            preserve_default=False,
        ),
    ]
